# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "crypto-service"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
no_fail_on_empty_changeset = true
s3_prefix = "crypto-service"
region = "us-west-2"
disable_rollback = true
parameter_overrides = "KMSKeyId=\"arn:aws:kms:us-west-2:438739839194:key/15d9cbfc-2ea1-48c2-accc-53847bbe56b2\""
image_repositories = []

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
stack_name = "crypto-service-prod"
s3_prefix = "crypto-service-prod"
region = "us-west-2"
no_fail_on_empty_changeset = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
