AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Lambda Encryption Service

  A serverless encryption service using AWS KMS for data encryption and decryption.
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 29
    MemorySize: 1024
    Runtime: nodejs22.x
    Architectures:
      - arm64
    Environment:
      Variables:
        NODE_PATH: ./node_modules:/opt/nodejs/node_modules

Parameters:
  KMSKeyId:
    Type: String
    Description: The KMS Key ARN to use for encryption and decryption
  ApiKeyValue:
    Type: String
    Description: The value for the API Key
    NoEcho: true  # Makes parameter value invisible in CloudFormation console

Resources:
  # API Gateway API definition
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true  # Enable API Key validation
      EndpointConfiguration: 
        Type: REGIONAL
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  # API Key definition
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn: ApiGatewayProdStage
    Properties:
      Enabled: true
      Name: crypto-service-api-key
      Value: !Ref ApiKeyValue
      Description: "API Key for Crypto Service"

  # Usage plan definition
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: ApiGatewayProdStage
    Properties:
      UsagePlanName: crypto-service-usage-plan
      Description: "Usage plan for Crypto Service"
      ApiStages:
        - ApiId: !Ref ApiGateway
          Stage: Prod

  # Associate API Key with usage plan
  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    DependsOn: 
      - ApiKey
      - UsagePlan
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello/
      Handler: app.lambdaHandler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /hello
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

  # Encryption function
  EncryptFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: encrypt/index.lambdaHandler
      Environment:
        Variables:
          KMS_KEY_ID: !Ref KMSKeyId
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - kms:Encrypt
                - kms:Decrypt
                - kms:GenerateDataKey
              Resource: !Ref KMSKeyId
      Events:
        Encrypt:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /encrypt
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - encrypt/index.ts
        - lib/crypto-utils.ts

  # Decryption function
  DecryptFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: decrypt/index.lambdaHandler
      Environment:
        Variables:
          KMS_KEY_ID: !Ref KMSKeyId
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - kms:Encrypt
                - kms:Decrypt
                - kms:GenerateDataKey
              Resource: !Ref KMSKeyId
      Events:
        Decrypt:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /decrypt
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - decrypt/index.ts
        - lib/crypto-utils.ts

Outputs:
  ApiGatewayUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ApiKeyId:
    Description: "API Key ID"
    Value: !Ref ApiKey
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  EncryptApi:
    Description: "API Gateway endpoint URL for Prod stage for Encrypt function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/encrypt/"
  DecryptApi:
    Description: "API Gateway endpoint URL for Prod stage for Decrypt function"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/decrypt/"
  EncryptFunction:
    Description: "Encrypt Lambda Function ARN"
    Value: !GetAtt EncryptFunction.Arn
  DecryptFunction:
    Description: "Decrypt Lambda Function ARN"
    Value: !GetAtt DecryptFunction.Arn
